### ISSUE TITLE
Characters Preceding IPs

### ISSUE THREAD

**Issue by laprjns** [jneilliii/OctoPrint-ActiveConnections#2]
Any idea why I see this?
![image](https://user-images.githubusercontent.com/5833597/150698978-19fb8484-6b79-4cc4-a129-8e4a6084379b.png)

**Comment by jneilliii** [comment]
Those are ipv6 addresses I believe. I assume your octopi is registering that way on the network and that's why you're getting those.

**Comment by jneilliii** [comment]
Available in version 0.2.0.
