### ISSUE TITLE
Display username associated with IP

### ISSUE THREAD

**Issue by mayhem5225** [jneilliii/OctoPrint-ActiveConnections#3]
Wonderful plugin!  I've been really waiting for this feature.

Would it be possible to also display the username?  I am thinking that could be pulled from the log file when a login event occurs.

Thanks!

**Comment by jneilliii** [comment]
I just took a quick look at the docs and this does seem to be something I could do.

**Comment by jneilliii** [comment]
Will be available in next release.

![image](https://user-images.githubusercontent.com/5249455/151257627-6874d6c7-7a59-43a2-b450-42690b5b5063.png)

**Comment by jneilliii** [comment]
Available in version 0.2.0 now.

**Comment by mayhem5225** [comment]
Wow, your quick!  Thanks.
