### ISSUE TITLE
Extra Character in front of IP address

### ISSUE THREAD

**Issue by rcassel52** [jneilliii/OctoPrint-ActiveConnections#4]
Small issue the add in has "::ffff:" in front of the IP addresses.   
![Issue](https://user-images.githubusercontent.com/17336787/151268774-81efafc8-10d2-4bc3-89e6-59127f89300b.jpg)

**Comment by jneilliii** [comment]
This literally was just addressed in version 0.2.0, see #2

**Comment by jneilliii** [comment]
you basically need to add `::ffff:` to the remove text in settings.
