### ISSUE TITLE
IP6 addresses overlaps the new username label

### ISSUE THREAD

**Issue by jonashogstrom** [jneilliii/OctoPrint-ActiveConnections#5]
![image](https://user-images.githubusercontent.com/1035652/151330892-2c783d64-33e3-40e7-80e4-bba393a71fce.png)

**Comment by jneilliii** [comment]
Thanks for reporting, I don't have ipv6 in my network so was unaware.

**Comment by jneilliii** [comment]
fixed in above commit and released as version 0.2.1.

**Comment by jonashogstrom** [comment]
Works like a charm. Thanks!
![image](https://user-images.githubusercontent.com/1035652/151753366-e5090bb8-4de1-4726-a026-6534d170bfdb.png)
